# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VicPtvCli < Formula
  desc "CLI for the Public Transport Victoria (PTV) Timetable API"
  homepage "https://github.com/bls/vic-ptv-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bls/vic-ptv-cli/releases/download/v0.1.0/vic-ptv-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "c030b705601009d3bd80db0a3fcc39e6eeba26f00eafbe4a42b0c842b842137d"

      def install
        bin.install "vic-ptv-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bls/vic-ptv-cli/releases/download/v0.1.0/vic-ptv-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "df3eb66de8e53524aa2d8159dc5432c37bec3952e6372d423759567c5d493b1c"

      def install
        bin.install "vic-ptv-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bls/vic-ptv-cli/releases/download/v0.1.0/vic-ptv-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "5b4e6b25e60fd765edf1bee8369739b32b75491a68f684196dadbeee907825c5"
      def install
        bin.install "vic-ptv-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bls/vic-ptv-cli/releases/download/v0.1.0/vic-ptv-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "74e4734684296e91f0e9644b59bb6eac27b78c2f3900e0f242c044ba7749cc8c"
      def install
        bin.install "vic-ptv-cli"
      end
    end
  end

  test do
    system "#{bin}/vic-ptv-cli", "--help"
  end
end
